/* FUNY PIN global i18n: ko/en */
(function(){
  const KEY='funy-pin-lang';
  const supported=['ko','en'];
  const stored=localStorage.getItem(KEY);
  let lang=supported.includes(stored)?stored:'ko';
  const path=location.pathname||'/';
  const isHome=/(^|\/)(index\.html)?$/.test(path);
  document.documentElement.lang=lang;
  document.body&&document.body.classList.toggle('funy-lang-home',isHome);

  const textMap={
    'by 깽퐌커플':{en:'by FFUNNYGGANG'},'홈':{en:'Home'},'리뷰':{en:'Reviews'},'리뷰•정보':{en:'Reviews · Info'},
    '카드샵 · FUNY PIN by 깽퐌커플':{en:'Card Shops · FUNY PIN by FFUNNYGGANG'},'리뷰 · FUNY PIN by 깽퐌커플':{en:'Reviews · FUNY PIN by FFUNNYGGANG'},
    '카드가 모이는 곳,':{en:'Where cards come together,'},'더 특별한 이야기가':{en:'where more special stories'},'시작되는 곳':{en:'begin.'},'FUNY PIN과 함께':{en:'With FUNY PIN,'},'내 취향의 카드샵을 찾아보세요!':{en:'find the card shop that fits your style!'},'카드샵 찾아보기':{en:'Find card shops'},'방문기 보기':{en:'View reviews'},'TCG MAP에서 카드샵 찾아보기':{en:'Find card shops on TCG MAP'},'더 보기':{en:'View more'},'카드샵 추천':{en:'Recommended card shops'},'깽퐌커플 카드샵 방문기':{en:'FFUNNYGGANG card shop visits'},'링크 모음':{en:'Links'},'깽퐌커플 링크 모음':{en:'FFUNNYGGANG links'},
    '직접 다녀온 카드샵':{en:'Card shops we visited'},'방문기와 정보를 한 곳에':{en:'Reviews and info in one place'},'직접 다녀온 카드샵\n방문기와 정보를 한 곳에':{en:'Card shops we visited\nReviews and info in one place'},'깽퐌커플이 직접 경험한 카드샵 후기와':{en:'Explore card shop reviews based on our visits'},'TCG 관련 콘텐츠를 확인해보세요.':{en:'and other TCG content.'},'다가오는 TCG 일정':{en:'Upcoming TCG Events'},'FUNY PIN 테스트 일정':{en:'FUNY PIN Test Event'},'캘린더 연동 전 UI 미리보기':{en:'Calendar UI preview'},
    '한국':{en:'Korea'},'일본':{en:'Japan'},'전체':{en:'All'},'포켓몬':{en:'Pokémon'},'원피스':{en:'One Piece'},'드래곤볼':{en:'Dragon Ball'},'싱글카드':{en:'Singles'},'등급카드':{en:'Graded cards'},'박스제품':{en:'Sealed boxes'},'오리파':{en:'Mystery packs'},'카드샵 이름 또는 지역으로 검색':{en:'Search by shop name or area'},'매장 위치를 불러오는 중...':{en:'Loading shop locations...'},'카드를 눌러 상세정보 보기':{en:'Tap a card to view details'},'조건에 맞는 카드샵이 없습니다.':{en:'No card shops match your filters.'},'일본 · 도쿄 · 아키하바라':{en:'Japan · Tokyo · Akihabara'},'서비스 준비 중입니다':{en:'Coming soon'},'내 위치':{en:'My location'},'추천 순':{en:'Recommended'},'가나다 순':{en:'A–Z'},'가까운 순':{en:'Nearest'},'카드샵 정렬':{en:'Sort card shops'},'국가 선택':{en:'Select country'},'검색어 지우기':{en:'Clear search'},'하단 메뉴':{en:'Bottom navigation'},
    '뒤로가기':{en:'Back'},'공유':{en:'Share'},'다른 카드샵 더 찾아보기':{en:'Find more card shops'},'기본 정보':{en:'Basic info'},'매장 정보':{en:'Shop info'},'영업시간':{en:'Hours'},'주소':{en:'Address'},'전화':{en:'Phone'},'전화하기':{en:'Call'},'홈페이지':{en:'Website'},'네이버지도':{en:'Naver Map'},'구글지도':{en:'Google Maps'},'방문 평점':{en:'Visit rating'},'매장 방문일':{en:'Visited'},'상품 구성 상세':{en:'Product mix'},'취급 TCG':{en:'TCG titles'},'깽퐌커플 리뷰':{en:'FFUNNYGGANG Reviews'},'매장 이미지 준비 중':{en:'Shop image coming soon'},'한눈에 보는 매장 분석':{en:'Shop analysis at a glance'},'※ 깽퐌커플 방문 평점 바탕으로 주관적인 분석으로 단순 참고용으로 활용해주세요.':{en:'※ This analysis is based on FFUNNYGGANG’s visit ratings and is for reference only.'},'도보':{en:'Walk'},'분':{en:'min'},'정보':{en:'Info'}
  };
  const attrNames=['placeholder','aria-label','title','alt'];const originalText=new WeakMap();const originalAttr=new WeakMap();
  function tr(value){if(lang==='ko')return value;const direct=textMap[value];if(direct&&direct[lang])return direct[lang];let out=value;Object.keys(textMap).sort((a,b)=>b.length-a.length).forEach(k=>{const translated=textMap[k]&&textMap[k][lang];if(translated&&out.includes(k))out=out.split(k).join(translated)});return out}
  function translateTextNode(node){if(!originalText.has(node))originalText.set(node,node.nodeValue);const base=originalText.get(node);node.nodeValue=lang==='ko'?base:tr(base)}
  function translateElement(el){if(!(el instanceof Element))return;if(el.closest&&el.closest('.funy-lang-switch'))return;attrNames.forEach(name=>{if(!el.hasAttribute(name))return;let store=originalAttr.get(el);if(!store){store={};originalAttr.set(el,store)}if(!(name in store))store[name]=el.getAttribute(name);const base=store[name];el.setAttribute(name,lang==='ko'?base:tr(base))})}
  function walk(root){if(!root)return;if(root.nodeType===Node.TEXT_NODE){translateTextNode(root);return}if(root.nodeType!==Node.ELEMENT_NODE&&root.nodeType!==Node.DOCUMENT_NODE)return;if(root.nodeType===Node.ELEMENT_NODE)translateElement(root);const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT|NodeFilter.SHOW_ELEMENT);let n;while((n=walker.nextNode())){if(n.nodeType===Node.TEXT_NODE)translateTextNode(n);else translateElement(n)}}
  function ensureTalkNav(){const nav=document.querySelector('.portal-bottom-nav');if(!nav||nav.querySelector('a[href="talk.html"]'))return;const css=document.createElement('link');css.rel='stylesheet';css.href='nav-v4.css?v=20260917-0548';document.head.appendChild(css);const a=document.createElement('a');a.href='talk.html';a.innerHTML='<svg viewBox="0 0 24 24"><path d="M4 5.5h16v11H9l-5 3v-14Z"/><path d="M8 10h.01M12 10h.01M16 10h.01"/></svg><span>TALK</span>';nav.appendChild(a)}
  function replaceReviewBanners(){if(!/(^|\/)reviews\.html$/.test(path))return;const imgs=document.querySelectorAll('.review-banner-slide img');const srcs=['assets/banners/banner_review_01.jpg','assets/banners/banner_review_02.jpg','assets/banners/banner_review_03.jpg'];imgs.forEach((img,i)=>{if(srcs[i])img.src=srcs[i]})}
  function ensureReviewScheduleUI(){if(!/(^|\/)reviews\.html$/.test(path)||document.querySelector('.review-schedule'))return;const banner=document.querySelector('.review-banner');if(!banner)return;const style=document.createElement('style');style.id='review-schedule-style';style.textContent='.review-schedule{margin:0 -14px;padding:20px 14px 24px;background:#fff}.review-schedule-head{display:flex;align-items:center;justify-content:space-between;margin:0 2px 12px}.review-schedule-title{margin:0;color:#1d1b24;font-size:17px;font-weight:800;letter-spacing:-.035em}.review-schedule-badge{display:inline-flex;align-items:center;height:22px;padding:0 8px;border-radius:999px;background:#f2edff;color:#7659cf;font-size:9px;font-weight:800;letter-spacing:.08em}.review-schedule-list{display:grid;gap:9px}.review-schedule-card{display:flex;align-items:center;gap:13px;padding:13px 14px;border:1px solid #ece8f2;border-radius:15px;background:#fff;box-shadow:0 5px 16px rgba(67,50,98,.055)}.review-schedule-date{display:flex;flex:0 0 48px;min-height:52px;flex-direction:column;align-items:center;justify-content:center;border-radius:12px;background:#f5f1ff;color:#7558cf}.review-schedule-month{font-size:9px;font-weight:800;letter-spacing:.06em}.review-schedule-day{margin-top:1px;font-size:20px;line-height:1;font-weight:850}.review-schedule-info{min-width:0;flex:1}.review-schedule-name{overflow:hidden;margin:0;color:#24212a;font-size:14px;font-weight:800;line-height:1.4;letter-spacing:-.025em;text-overflow:ellipsis;white-space:nowrap}.review-schedule-meta{margin:5px 0 0;color:#99939f;font-size:11px;line-height:1.4}.review-schedule-arrow{flex:0 0 auto;color:#b2abbc;font-size:18px;line-height:1}@media(max-width:430px){.review-schedule{padding-top:18px;padding-bottom:22px}.review-schedule-title{font-size:16px}.review-schedule-card{padding:12px 13px}}';document.head.appendChild(style);const section=document.createElement('section');section.className='review-schedule';section.setAttribute('aria-label','다가오는 TCG 일정');section.innerHTML='<div class="review-schedule-head"><h2 class="review-schedule-title">다가오는 TCG 일정</h2><span class="review-schedule-badge">CALENDAR</span></div><div class="review-schedule-list"><article class="review-schedule-card"><div class="review-schedule-date"><span class="review-schedule-month">SEP</span><strong class="review-schedule-day">19</strong></div><div class="review-schedule-info"><h3 class="review-schedule-name">FUNY PIN 테스트 일정</h3><p class="review-schedule-meta">서울 · 캘린더 연동 전 UI 미리보기</p></div><span class="review-schedule-arrow" aria-hidden="true">›</span></article></div></section>';banner.insertAdjacentElement('afterend',section)}
  function renderSwitch(){if(!isHome)return;if(document.querySelector('.funy-lang-switch'))return;const wrap=document.createElement('div');wrap.className='funy-lang-switch';wrap.setAttribute('role','group');wrap.setAttribute('aria-label',lang==='ko'?'언어 선택':'Language');wrap.innerHTML='<button type="button" data-funy-lang="ko">KO</button><button type="button" data-funy-lang="en">EN</button>';document.body.appendChild(wrap);syncSwitch();wrap.addEventListener('click',e=>{const btn=e.target.closest('[data-funy-lang]');if(!btn)return;const next=btn.dataset.funyLang;if(!supported.includes(next)||next===lang)return;localStorage.setItem(KEY,next);location.reload()})}
  function syncSwitch(){document.querySelectorAll('[data-funy-lang]').forEach(btn=>btn.setAttribute('aria-pressed',String(btn.dataset.funyLang===lang)))}
  function apply(){ensureTalkNav();replaceReviewBanners();ensureReviewScheduleUI();document.documentElement.lang=lang;document.body.classList.toggle('funy-lang-home',isHome);walk(document.body);document.title=lang==='ko'?(originalText.get(document.querySelector('title'))||document.title):tr(document.title);renderSwitch();syncSwitch();window.dispatchEvent(new CustomEvent('funy:languagechange',{detail:{lang}}))}
  const observer=new MutationObserver(mutations=>{mutations.forEach(m=>m.addedNodes.forEach(node=>{if(node.nodeType===1&&node.closest&&node.closest('.funy-lang-switch'))return;walk(node)}))});
  function start(){apply();observer.observe(document.body,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();window.FUNY_I18N={getLang:()=>lang,setLang(next){if(!supported.includes(next))return;localStorage.setItem(KEY,next);location.reload()},t:tr};
})();
