import { useEffect,useMemo,useRef,useState } from 'react';
import { useRouter } from 'expo-router';
import { ActivityIndicator,FlatList,Modal,Platform,Pressable,SafeAreaView,ScrollView,Text,TextInput,View } from 'react-native';
import MapView,{Callout,Marker,PROVIDER_GOOGLE,Region} from 'react-native-maps';
import * as Location from 'expo-location';
import { AppShop,FunyMonEvent,getActiveFunyMonEvents,getShops } from '../../lib/shops';
import FunyHeader from '../../components/FunyHeader';
import { C,shadow } from '../../lib/theme';

const REGIONS:Record<'KR'|'JP',Region>={KR:{latitude:37.5665,longitude:126.978,latitudeDelta:.18,longitudeDelta:.18},JP:{latitude:35.6812,longitude:139.7671,latitudeDelta:.18,longitudeDelta:.18}};
const FILTERS=[['pokemon','포켓몬','tcg'],['onepiece','원피스','tcg'],['dragonball','드래곤볼','tcg'],['single','싱글카드','feature'],['graded','등급카드','feature'],['vintage','빈티지카드','feature'],['oripa','오리파','feature'],['box','박스제품','feature'],['unmanned','무인매장','feature']] as const;
type Sort='recommended'|'name'|'distance';
const km=(a:{latitude:number;longitude:number},b:AppShop)=>{const r=6371,d=Math.PI/180,x=(Number(b.latitude)-a.latitude)*d,y=(Number(b.longitude)-a.longitude)*d,q=Math.sin(x/2)**2+Math.cos(a.latitude*d)*Math.cos(Number(b.latitude)*d)*Math.sin(y/2)**2;return 2*r*Math.asin(Math.sqrt(q))};

export default function MapScreen(){
  const router=useRouter(),map=useRef<MapView>(null),[shops,setShops]=useState<AppShop[]>([]),[events,setEvents]=useState<FunyMonEvent[]>([]),[q,setQ]=useState(''),[country,setCountry]=useState<'KR'|'JP'>('KR'),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[locating,setLocating]=useState(false),[filterOpen,setFilterOpen]=useState(false),[filters,setFilters]=useState<string[]>([]),[sort,setSort]=useState<Sort>('recommended'),[me,setMe]=useState<{latitude:number;longitude:number}|null>(null);
  useEffect(()=>{Promise.all([getShops(),getActiveFunyMonEvents()]).then(([s,e])=>{setShops(s);setEvents(e)}).catch(e=>setError(String(e.message||e)))},[]);
  const eventByShop=useMemo(()=>new Map(events.filter(e=>e.shop_id).map(e=>[e.shop_id as string,e])),[events]);
  const list=useMemo(()=>{const k=q.trim().toLowerCase(),active=FILTERS.filter(x=>filters.includes(x[0]));let a=shops.filter(s=>s.country_code===country&&(!k||[s.name,s.name_en,s.city,s.area,s.address].some(v=>String(v||'').toLowerCase().includes(k)))&&active.every(([id,,type])=>type==='tcg'?s.tcg?.[id]?.status===true:s.features?.[id]?.value===true));if(sort==='recommended')a=[...a].sort((x,y)=>Number(eventByShop.has(y.id))-Number(eventByShop.has(x.id)));if(sort==='name')a=[...a].sort((x,y)=>x.name.localeCompare(y.name,'ko'));if(sort==='distance'&&me)a=[...a].sort((x,y)=>km(me,x)-km(me,y));return a},[shops,q,country,filters,sort,me,eventByShop]);
  const changeCountry=(c:'KR'|'JP')=>{setCountry(c);setSelected(null);map.current?.animateToRegion(REGIONS[c],350)};
  const focus=(s:AppShop)=>{setSelected(s.id);map.current?.animateToRegion({latitude:Number(s.latitude),longitude:Number(s.longitude),latitudeDelta:.018,longitudeDelta:.018},300)};
  const locate=async()=>{setLocating(true);try{const p=await Location.requestForegroundPermissionsAsync();if(p.status!=='granted')return;const x=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced}),pos={latitude:x.coords.latitude,longitude:x.coords.longitude};setMe(pos);map.current?.animateToRegion({...pos,latitudeDelta:.018,longitudeDelta:.018},300)}finally{setLocating(false)}};
  const chip=(on:boolean)=>({height:34,paddingHorizontal:13,borderRadius:18,borderWidth:1,borderColor:on?C.purple:C.line,backgroundColor:on?C.purple:'#fff',alignItems:'center' as const,justifyContent:'center' as const});
  return <SafeAreaView style={{flex:1,backgroundColor:C.bg}}>
    <FunyHeader/>
    <View style={{paddingHorizontal:14,paddingTop:14,flex:1}}>
      <Text style={{fontSize:10,fontWeight:'800',letterSpacing:2,color:'#9C92B5'}}>FIND YOUR CARD SHOP</Text>
      <Text style={{marginTop:4,fontSize:24,fontWeight:'900',letterSpacing:-.7,color:C.text}}>TCG MAP</Text>
      <TextInput value={q} onChangeText={setQ} placeholder="카드샵 이름 또는 지역으로 검색" placeholderTextColor="#A39DA8" style={{marginTop:12,height:46,borderWidth:1,borderColor:C.line,borderRadius:14,paddingHorizontal:14,backgroundColor:'#fff',color:C.text,...shadow}}/>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{flexGrow:0}} contentContainerStyle={{gap:7,paddingTop:10,paddingBottom:12}}>
        {(['KR','JP'] as const).map(c=><Pressable key={c} onPress={()=>changeCountry(c)} style={chip(country===c)}><Text style={{fontWeight:'800',fontSize:12,color:country===c?'#fff':'#6F6976'}}>{c==='KR'?'대한민국':'일본'}</Text></Pressable>)}
        <Pressable onPress={()=>setFilterOpen(true)} style={chip(filters.length>0)}><Text style={{fontWeight:'800',fontSize:12,color:filters.length?'#fff':'#6F6976'}}>필터{filters.length?` ${filters.length}`:''}</Text></Pressable>
        <Pressable onPress={locate} style={chip(false)}><Text style={{fontWeight:'800',fontSize:12,color:'#6F6976'}}>{locating?'확인 중…':'내 위치'}</Text></Pressable>
      </ScrollView>
      <View style={{height:255,borderRadius:18,overflow:'hidden',backgroundColor:'#EEEAF4',...shadow}}>
        <MapView ref={map} provider={Platform.OS==='android'?PROVIDER_GOOGLE:undefined} style={{flex:1}} initialRegion={REGIONS.KR} showsUserLocation showsMyLocationButton={false}>
          {list.map(s=>{const ev=eventByShop.get(s.id);return <Marker key={s.id} coordinate={{latitude:Number(s.latitude),longitude:Number(s.longitude)}} pinColor={ev?C.purple:selected===s.id?C.purpleDark:undefined} onPress={()=>setSelected(s.id)}><Callout onPress={()=>router.push(`/shop/${s.id}`)}><View style={{width:190,padding:4}}><Text style={{fontWeight:'900'}}>{s.name}</Text>{ev?<Text style={{marginTop:4,fontSize:12,fontWeight:'800'}}>✨ {ev.title}</Text>:null}<Text style={{marginTop:4,fontSize:11,color:'#666'}}>{s.area||s.address}</Text><Text style={{marginTop:7,fontSize:11,fontWeight:'800',color:C.purpleDark}}>상세보기 ›</Text></View></Callout></Marker>})}
        </MapView>
      </View>
      {error?<Text style={{marginTop:12,color:C.danger}}>{error}</Text>:shops.length===0?<ActivityIndicator style={{marginTop:20}} color={C.purple}/>:<FlatList style={{marginTop:14}} contentContainerStyle={{paddingBottom:110}} data={list} keyExtractor={x=>x.id} ListHeaderComponent={<View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:8,paddingHorizontal:2}}><View><Text style={{fontSize:10,color:'#9C92B5',fontWeight:'800',letterSpacing:1.3}}>CARD SHOP LIST</Text><Text style={{marginTop:3,fontWeight:'900',color:C.text}}>카드샵 {list.length}곳</Text></View><View style={{flexDirection:'row',gap:10}}>{([['recommended','추천순'],['name','이름순'],['distance','거리순']] as [Sort,string][]).map(([v,t])=><Pressable key={v} onPress={()=>{if(v==='distance'&&!me)locate();setSort(v)}}><Text style={{fontSize:11,fontWeight:sort===v?'900':'500',color:sort===v?C.purpleDark:'#918A95'}}>{t}</Text></Pressable>)}</View></View>} renderItem={({item})=>{const ev=eventByShop.get(item.id);return <Pressable onPress={()=>{focus(item);router.push(`/shop/${item.id}`)}} style={{marginBottom:8,padding:14,borderWidth:1,borderColor:C.line,borderRadius:16,backgroundColor:'#fff',...shadow}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Text style={{fontSize:15,fontWeight:'900',color:C.text}}>{item.name}</Text>{me?<Text style={{fontSize:11,color:'#8A8490'}}>{km(me,item).toFixed(1)}km</Text>:null}</View>{ev?<Text style={{marginTop:5,fontSize:12,fontWeight:'800',color:C.purpleDark}}>✨ {ev.title}</Text>:null}<Text numberOfLines={1} style={{marginTop:5,fontSize:12,color:'#77717C'}}>{item.area||item.city} · {item.address}</Text></Pressable>}}/>}
      <Modal visible={filterOpen} transparent animationType="slide" onRequestClose={()=>setFilterOpen(false)}><Pressable onPress={()=>setFilterOpen(false)} style={{flex:1,backgroundColor:'#0006',justifyContent:'flex-end'}}><Pressable onPress={()=>{}} style={{backgroundColor:'#fff',borderTopLeftRadius:24,borderTopRightRadius:24,padding:20,paddingBottom:34}}><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={{fontSize:20,fontWeight:'900'}}>필터</Text><Pressable onPress={()=>setFilters([])}><Text style={{color:C.muted}}>초기화</Text></Pressable></View><ScrollView style={{marginTop:16}} contentContainerStyle={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{FILTERS.map(([id,label])=>{const on=filters.includes(id);return <Pressable key={id} onPress={()=>setFilters(x=>on?x.filter(v=>v!==id):[...x,id])} style={{paddingHorizontal:13,paddingVertical:9,borderRadius:20,borderWidth:1,borderColor:on?C.purple:C.line,backgroundColor:on?C.purpleSoft:'#fff'}}><Text style={{fontWeight:on?'800':'500',color:on?C.purpleDark:'#6F6976'}}>{label}</Text></Pressable>})}</ScrollView><Pressable onPress={()=>setFilterOpen(false)} style={{marginTop:22,padding:15,borderRadius:14,backgroundColor:C.purple}}><Text style={{color:'#fff',textAlign:'center',fontWeight:'900'}}>{list.length}개 매장 보기</Text></Pressable></Pressable></Pressable></Modal>
    </View>
  </SafeAreaView>;
}
